baseurl: "https://toronto-crypto-day.github.io/"
title: "Toronto Crypto Day"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: ""

params:
  # Conference info
  Name: "Toronto Crypto Day"
  Description: "A full day of cryptography talks in the Toronto Area"
  Date: "November 3 2023"
  # Price: "Only $100" # If your event is free, just comment this line
  Venue: "Sorry Studios"
  Address: "61 Elm Grove Ave"
  City:  "Toronto"
  State: "Ontario"
  Images: ["/img/badge.jpg"]
  # GoogleMapsKey: "my-secret-maps-key"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    #- location
    - speakers
    - schedule
    - sponsors
    # - partners
    #- contact

  # Titles which you can translate to other languages
  Titles:
    about: "About"
    location: "Location"
    speakers: "Speakers"
    schedule: "Schedule"
    sponsors: "Sponsors"
    partners: "Partners"
    contact: "Contact"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
    text: "Register now!"
    link: "https://cryptpad.fr/form/#/3/form/view/8f175d3cc218fc13eedaea991acda30a/ "

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
  #ForkButton:
  #  repository: "https://github.com/jweslley/hugo-conference/"

  # List of Sponsors
  Sponsors:
    - name: "HashCloak"
      logo: "/img/hashcloak_logo_colour-logo-text.png"
      url: "http://hashcloak.com"

  # The entire schedule
  Schedule:
    - name: "Mikerah Quintyne-Collins"
    #   photo: "/img/speaker.jpg"
      bio: "Mikerah Quintyne-Collins is an independent researcher and founder and CEO of HashCloak, a blockchain privacy R&D startup with a global team. Her research focuses on networking, validator privacy, and optimistic rollups. She organized Scaling Ethereum, a research workshop bringing together top Ethereum researchers to work on Ethereum’s most pressing scalability problems. Currently, she’s focused on privacy for blockchains, specifically mixers and mix networks for cryptocurrency transactions. Previously, she was part of the ChainSafe Systems team working on ETH2.0, namely the Lodestar Typescript client. She was awarded a Vitalik YOLO grant for her work on ETH2.0."
      company: "HashCloak Inc"
      link:
        href: "http://twitter.com/badcryptobitch"
        text: "@badcryptobitch"
      presentation:
        title: "How to design a VM for MPC"
        description: "Multiparty computation is a cryptographic primitive in which multiple parties compute over private inputs a public function. MPC has seen a increase in industrial usage, particularly as it pertains to securing cryptographic keys. In order to use MPC in other applications, there has been academic effort into designing frameworks which abstract away the details of building MPC enabled applications similar to those for zk-snarks such as Circom. In this talk, we will go over the design and architecture of two popular MPC frameworks, MP-SPDZ and SCALE-MAMBA. We will go into details about their VM design and what makes their VMs amenable to MPC computation"
        time: "10h00"

    - name: "0xBankisan"
    #   photo: "/img/speaker.jpg"
      bio: "Spiro is a crypto founder building a private multiparty wallet on Ethereum. He has developed DeFi protocols, audit tooling, and is a hobbyist cryptographer. In the past, he worked as a software engineer in data, infra, and backend applications at Uber, Lazer, and other web companies."
      company: "Independent"
      link:
        href: "http://twitter.com/0xbankisan"
        text: "@0xbankisan"
      presentation:
        title: "Building zkShield: The hard parts of building consumer ZK"
        description: "I'm going to cover a quick overview of ZKPs, how they are implemented in code (solidity), the limitations of zkECDSAs, and general browser proving and verifying for for consumer products."
        time: "11h00"

    - name: "Lunch"
      time: "12h00"

    - name: "Mohammad Jahanara"
    #   photo: "/img/speaker.jpg"
      bio: "Mo is a senior protocol researcher at Scroll Foundation. Prior to this role, he served as a research engineer at Quantstamp and as a blockchain developer at Aquanow. His research interests encompass protocol design, proof systems, and privacy-enhancing technologies"
      company: "Scroll Foundation"
      link:
        href: "http://twitter.com/MMJahanara"
        text: "@MMJahanara"
      presentation:
        title: "Mempool Encryption via Multiparty Delay Encryption"
        description: "Ethereum is a decentralized and permissionless network offering several attractive features. However, block generation is ephemerally centralized, and proposers in Ethereum can exploit the order of transactions to extract value. This phenomenon, known as maximal extractable value (MEV), not only disrupts the optimal functioning of different protocols but also undermines the stability of the underlying consensus mechanism.

A prominent approach to alleviate MEV extraction is through mempool privacy, which involves keeping transaction content hidden before their execution in blocks. In this talk, we delve into the concept of mempool encryption, discussing proposed constructions and their limitations. The talk is based on joint work with Amirhossein Khajehpour, Hanzaleh Akbarinodehi, and Chen Feng"
        time: "13h00"

    # - name: "Steve Jobs"
    #   photo: "/img/speaker.jpg"
    #   bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
    #   company: "Apple, Inc."
    #   link:
    #     href: "http://github.com/stevie"
    #     text: "@stevie"
    #   presentation:
    #     title: "Presenting iPad"
    #     description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
    #     time: "14h00"

    # - name: "Coffee-break"
    #   time: "15h00"

    # - name: "Mark Zuckerberg"
    #   photo: "/img/speaker.jpg"
    #   bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
    #   company: "Facebook"
    #   link:
    #     href: "http://twitter.com/zuck"
    #     text: "@zuck"
    #   presentation:
    #     title: "Revealing Facebook Secrets"
    #     description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
    #     time: "16h00"

    # - name: "Steve Wozniak"
    #   photo: "/img/speaker.jpg"
    #   bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
    #   company: "Apple, Inc."
    #   link:
    #     href: "http://twitter.com/woz"
    #     text: "@woz"
    #   presentation:
    #     title: "Why do I prefer Android over iPhone"
    #     description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
    #     time: "17h00"
